### ISSUE TITLE
Failed task: Add root postgresql user during deployment

### ISSUE THREAD

**Issue by MaroGM** [leihs/leihs-instance#1]
Ansible deployment fails with 

```
TASK [postgresql : add root postgresql user] *********************************************************************************************************************************************************
fatal: [192.168.178.28]: FAILED! => {"changed": false, "msg": "Failed to create remote module tmp path at dir /tmp/ansible_leihs_deploy with prefix ansible-moduletmp-1543145348.23-: [Errno 13] Permission denied: '/tmp/ansible_leihs_deploy/ansible-moduletmp-1543145348.23-g0zrXx'"}

PLAY RECAP *******************************************************************************************************************************************************************************************
192.168.178.28             : ok=27   changed=5    unreachable=0    failed=1
```

Occurs with fresh virtual machines in Ubuntu 18.04 and Debian 9.6.0 (both amd64). Deployment via root user to local virtual machines for testing purposes.

**Comment by eins78** [comment]
I can not reproduce this with a fresh VM (Debian 9). The error message indicates that something is wrong with your VM setup. The error stems from ansible not being able to execute a command because the connecting user does not have proper permissions for the temp. directory – by definition this can't be fixed or repaired using ansible.
It also seems strange to me that this error pops up rather late in the playbook, after many steps have already been executed (using the same temp. dir…).

Anyways, the project is in kind of a "between" phase right now. We have released version 5.0, which we cant guarantee works for all external ando/or exisiting instances and therefore this template was not updated yet.

For your testing purposes, it might be best you try the newest release candidate, which contains many improvements regarding the deploy. And, more importantly we won't spend any more ressources on the old version, while we would of course fix any issues with our code that might appear for version 5.0 and later.


Try the following:

```sh
# setup debian 9 w/ root login, follow instructions from GUIDE.md
./scripts/update_leihs_latest v/5.0-staging
git submodule update --recursive --init --force
./scripts/deploy
```

**Comment by MaroGM** [comment]
Clear re: phase transition - and will try the suggestion. Thanks for trying to reproduce! I'll keep looking for what could be the issue if the suggestion does not pan out.

**Comment by sbonaime** [comment]
Hi,
I have the same problem with latest git version. I also tried @eins78 proposition without sucess. Is there something I can try ? 

```
fatal: [XXXX]: FAILED! => {"changed": false, "msg": "Failed to create remote module tmp path at dir /tmp/ansible with prefix ansible-moduletmp-1552905751.25-: [Errno 13] Permission denied: '/tmp/ansible/ansible-moduletmp-1552905751.25-ArPv71'"}
```

**Comment by sbonaime** [comment]
I solved this problem by modifying leihs/deploy/roles/postgresql/tasks/main.yml like that
````
- include: install.yml

- include: monitor.yml

- file: 
    path: /tmp/ansible
    owner: root
    group: root
    mode: 0777
    
- name: add root postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: root
    role_attr_flags: CREATEDB,SUPERUSER
    password: root
  tags: debug

- postgresql_db:
    name: root
    login_user: root
    owner: root
  name: Create the a database for root

````
